services:

  url_shortener_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortener_backend
    ports:
      - "4000:4000"
    expose:
      - "4000"
    volumes:
      - .:/app
      - /app/node_modules

  url_shortener_db:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    container_name: url_shortener_db
    volumes:
      - ~/apps/url_shortener_db:/var/lib/posgresql/data
    ports:
      - "4001:4001"
    expose:
      - "4001"
    command: -p 4001
